version: '3.3'

services:
  jenkins:
    image: jenkins:2.60.3
    ports: [ "8280:8080" ]
    volumes:
    - jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins:
