version: '3.3'

services:
  jenkins:
    image: treeptik/jenkins:lts
    ports: [ "8280:8080" ]
    volumes:
    - jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins:
